export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { prisma, hasDB } from "@/lib/db";
const today = () => new Date().toISOString().slice(0,10);
const nDaysAgo = (n:number) => { const d=new Date(); d.setDate(d.getDate()-n); return d.toISOString().slice(0,10); };
const fmt = (d:string) => new Date(d+"T12:00:00").toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"});
export async function GET(req: NextRequest) {
  const sp = new URL(req.url).searchParams;
  const start = sp.get("start")||nDaysAgo(30), end = sp.get("end")||today();
  if (!hasDB) return NextResponse.json({ error:"No data in range" }, { status:404 });
  let logs: Awaited<ReturnType<typeof prisma.dailyLog.findMany>> = [];
  try { logs = await prisma.dailyLog.findMany({ where:{date:{gte:start,lte:end}}, orderBy:{date:"asc"} }); } catch { /* no db */ }
  if (!logs.length) return NextResponse.json({ error:"No data in range" }, { status:404 });
  const ml = logs.filter(l=>l.hasMigraine), td=logs.length, tm=ml.length;
  const mf = parseFloat(((tm/td)*100).toFixed(1));
  const as = tm>0?parseFloat((ml.reduce((s,l)=>s+l.migraineSeverity,0)/tm).toFixed(1)):0;
  const ad = tm>0?parseFloat((ml.reduce((s,l)=>s+l.migraineDuration,0)/tm).toFixed(1)):0;
  const tlh = ml.reduce((s,l)=>s+l.migraineDuration,0);
  const avgSleep = parseFloat((logs.reduce((s,l)=>s+l.sleepHours,0)/td).toFixed(1));
  const avgStress = parseFloat((logs.reduce((s,l)=>s+l.stressLevel,0)/td).toFixed(1));
  const exDays = logs.filter(l=>l.exercise).length;
  const rm: Record<string,{count:number;ratingTotal:number}> = {};
  ml.forEach(l=>{ let ms:string[]=[]; try{ms=JSON.parse(l.reliefMethods);}catch{/**/} ms.forEach(m=>{ if(!rm[m]) rm[m]={count:0,ratingTotal:0}; rm[m].count++; rm[m].ratingTotal+=l.reliefRating; }); });
  const topReliefMethods = Object.entries(rm).map(([m,d])=>({method:m,count:d.count,avgRating:parseFloat((d.ratingTotal/d.count).toFixed(1))})).sort((a,b)=>b.avgRating-a.avgRating).slice(0,5);
  const summary = `MIGRAINE REPORT — ${fmt(start)} to ${fmt(end)}\n${"─".repeat(50)}\n\nOVERVIEW\n  Tracking period : ${td} days (${start} → ${end})\n  Total migraines : ${tm}\n  Frequency       : ${mf}% of days\n  Avg severity    : ${as}/10\n  Avg duration    : ${ad} hours\n  Total lost hrs  : ${tlh.toFixed(1)} hours\n\nLIFESTYLE AVERAGES\n  Avg sleep       : ${avgSleep} hrs/night\n  Avg stress      : ${avgStress}/5\n  Exercise days   : ${exDays}/${td} days\n\nTOP RELIEF METHODS\n${topReliefMethods.map((m,i)=>`  ${i+1}. ${m.method} — used ${m.count}×, avg rating ${m.avgRating}/5`).join("\n")}\n\nMIGRAINE DATES\n${ml.map(l=>`  ${l.date}  severity ${l.migraineSeverity}/10  duration ${l.migraineDuration}h`).join("\n")}\n\n${"─".repeat(50)}\nGenerated by Migraine Forecast on ${today()}`.trim();
  return NextResponse.json({ range:{start,end}, stats:{totalDays:td,totalMigraines:tm,migraineFrequency:mf,avgSeverity:as,avgDuration:ad,totalDisabledHours:tlh,avgSleep,avgStress,exerciseDays:exDays}, topReliefMethods, migraineDates:ml.map(l=>({date:l.date,severity:l.migraineSeverity,duration:l.migraineDuration})), plainTextSummary:summary });
}
